name: Rebuild Mkosi images for nspawn.org

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Also run on cron schedule
  schedule:
    - cron: 0 0 * * 0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: internal-builders
    defaults:
      run:
        working-directory: hub-images

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      # Check duplictaed outputs
      - name: Check for duplicated Output directives
        run: |
          ./validate_directories.sh

      # Prepare our custom builder
      - name: Prepare our builder
        run: |
          sudo apt-get install --assume-yes --no-install-recommends debian-archive-keyring

      # Configure GPG
      - name: Configure the GPG Key
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | sudo gpg --import

      # Setup mkosi
      - name: setup-mkosi
        uses: systemd/mkosi@main
            
      #- name: Debug
      #  uses: mxschmitt/action-tmate@v3

      - name: Change ownership of files for checkout
        run: sudo chown -R $USER:$USER $PWD
        
      # Clean newly created directories to avoid the build.sh script tryting to iterate them
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build the images
        run: |
          sudo ./build.sh
          sudo ./clean-artifacts.sh
          
      #- name: Debug
      #  uses: mxschmitt/action-tmate@v3

        # Prepare everything for syncing
      - name: Install SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_VM1_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/nspawnvm1.key
          chmod 400 ~/.ssh/nspawnvm1.key

      - name: Adding Known Hosts
        run: |
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.SSH_VM1_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # Finally deploy the artifacts
      - name: Deploy with rsync
        run: rsync -e "ssh -i ~/.ssh/nspawnvm1.key" -auvzP ./output/public/storage/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_VM1_HOST }}:/var/www/hub-nspawn/storage/
        
      - uses: gautamkrishnar/keepalive-workflow@v1    
